language: php
os: linux

php:
  - 7.4
  - nightly # testing on PHP 8 with an actual WeakMap ensures that our tests are valid

jobs:
  allow_failures:
    - php: nightly

before_script:
  - composer install --ignore-platform-reqs

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - vendor/bin/php-coveralls -v
